### ISSUE TITLE
Use Github Actions for packaging

### ISSUE THREAD

**Issue by emersonrp** [emersonrp/bindcontrol#12]
Work to use Github Actions to automate some of the busywork around automated testing and packaging of new releases.

**Comment by JamzTheMan** [comment]
this should be pretty easy to do, if you can list out the steps you do to create the .exe and package it up, I can fork the repo and put a PR together.

FYI: there are windows/mac/linux VM's available if it helps create executables for other OS's or run tests.

**Comment by emersonrp** [comment]
Currently the steps are a little extra because (right now, on Win11) I swap between WSL for editing and git wrangling and Git-Cmd for making the actual windows ZIP/bundle.  (In my home setup, I'm running Manjaro, and I do the Git-Cmd steps via a Win10 VM.)  Basic outline:

-- WSL: Check everything in.
-- WSL: Add git tag "v0.50.0" or whatever
-- WSL: Push it to github
-- Git-Cmd: Make sure windows side is pulled and checked out to the right tag
-- Git-Cmd: run tools\build_windows.bat (relies on git, and on pyinstaller having been installed via pip)
-- that spits out the correctly-named ZIP file, which I upload into a new release.

Most of it happens in tools\build_windows.bat, but it's not super smart or complicated and will cheerfully build a ZIP of whatever crap is lying around in the workdir, which is part of why I do the tinkering over elsewhere and use Git-Cmd just for tracking what's currently up on github with zero editing or changes.

I can imagine a github actions world where both of the "Git-Cmd" steps listed above just happen automagically when I upload a new tag or draft a new release or something.  That would be shiny, not having to switch to doing anything in a Windows terminal session at all.

Exe's for other OSes are on my radar but I'm not there yet.  Maybe if this process works out, I can build containers for Linux.  MacOS might just be right out since it absolutely requires code signing.  Really in a perfect world, everyone just checks out the repo and installs python and wx, but we don't live in that world...  ;)

**Comment by JamzTheMan** [comment]
Looks pretty simple, I was able to build and zip locally! I'll see what I can knock out.

**Comment by JamzTheMan** [comment]
PR Submitted :)

Windows zip tested and downloads without tripping any virus warning on my end and exe works as expected!

I left a commented block out for Linux, not sure why but it generates a 133mb file, think it's large libs from wxPython.  Also not sure how to test, I tried testing with wsl and got error, but feel free to adjust the PyInstaller as needed and test (as I just realized you had different build scripts)
