### ISSUE TITLE
Mystic Flight SoD binds try to insert Hover, even if you don't have Flight Pool.

### ISSUE THREAD

**Issue by xizar** [emersonrp/bindcontrol#15]
The "Player has Hover" tickbox status does not check to see if you have the flight pool meaning that you can have a situation where Mystic Flight will try to insert Hover into the bind files.  (I only checked Bo000000.txt; I assume other ones are compromised as mystic flight would detoggle in-game.)

This can be fixed manually by enabling Flight as a power pool, going to the SoD tab, un-ticking the Hover box (while it's no longer grey-ed out) and then removing Flight again.

(perhaps related, "Hide Windows when Teleporting" doesn't work for Mystic Flight's translocate)

**Comment by emersonrp** [comment]
Apologies for the delay in getting to these. Real life is happening a lot right now.

Anyway, the mystic flight vs hover problem is probably a pretty quick fix and I'll see if I can get something released in the next couple of days.

The hide windows issue might be more tangly, as it involves digging around inside the somewhat arcane teleport logic that bindcontrol inherited from citybinder. It might be simple, it might not. I'll update here as I know things. 

Thanks!

**Comment by xizar** [comment]
(Perhaps the wrong place for a feature request/enhancement: could you set Teleport to happen on key-release, so that we can target a destination rather than immediately triggering to wherever the cursor is when hitting the key?)

**Comment by emersonrp** [comment]
Working on the Mystic Flight / Hover misbehavior.  It's a bit tanglier than I'd hoped.  (The speed-on-demand code is a sort of a cryptic black box that's been through three different languages and programs on its way to bindcontrol, so weaving things into it is a bit fraught with peril, heh.)  I should have something later today, knock wood.

For the teleport-on-release thing, that seems also not trivial, but I like the idea.  Please open a new issue for that and we can track it there.

**Comment by emersonrp** [comment]
Would it be a good solution to change it up where Translocation is selectable as the main teleport power, instead of it having its own key?  Then it would automatically inherit all of the binding behavior of normal teleport.  The only downside I could see is if someone for some reason wanted to use both Translocation and Teleport separately.  Any thoughts on this as a solution to the hiding-windows behavior?

**Comment by xizar** [comment]
I think allowing the selection of which teleport power to use as a default before writing the bind files would be okay.  I don't know how viable (or even reasonable) it would be to set up a hotkey to toggle in game which power to use.  It would be nice to use the teleport reticle with translocate, though.

I do think that setting Mystic Flight/Translocate as the primary teleport power would be awkward as you'd have to make sure that Mystic Flight is running before invoking Translocate, and I don't think the game lets you do that.

**Comment by emersonrp** [comment]
This bug was, I think, fixed in release v0.14.4.1 so I am closing it.  If there's still problems specifically with the availability of Hover, please comment and re-open it.
