### ISSUE TITLE
Allow user defined default save locations for profiles.

### ISSUE THREAD

**Issue by xizar** [emersonrp/bindcontrol#17]
It would be nice if we could choose where to put profiles files.  My particular installation has CoX installed on a NAS, with sundry support software in a directory nested below.  (This is mostly so I have an extra copy of bind profiles and costumes laying around rather than on my local drive.)

**Comment by emersonrp** [comment]
This should be pretty trivial.  It's currently set up to save profiles to the standard "Documents" location for whatever platform you're running on, but it should be possible to make that be the default and allow for a directory picker to pick a custom location.  I'll try to get that in there sooner than later.

**Comment by emersonrp** [comment]
I have this working now, and it will be part of release 0.14.2

**Comment by emersonrp** [comment]
I've released 0.14.2.1 which contains this change -- the profile path is settable in the Preferences dialog.

**Comment by emersonrp** [comment]
This was addressed in v0.14.2.1, closing this.  Please re-open it if you have any trouble with the custom profile location.
