### ISSUE TITLE
"UP" for Fly is misconfigured (doesn't swap hover/fly, doesn't turn off fly when you release key) (v0.15.0.3)

### ISSUE THREAD

**Issue by xizar** [emersonrp/bindcontrol#28]
Going up from hovering turns on Fly but does not turn off Hover.  stopping going up stops you from going up, but does not turn off Fly

showbind "space" while Fly is on

>  +down$$up 1$$down 0$$forward 0$$backward 0$$left 0$$right 0$$powexectoggleon Fly$$bindloadfilesilent F:\TCB\RedWater\F\F100000.txt

showbind "space" while Fly is off

>  +down$$up 1$$down 0$$forward 0$$backward 0$$left 0$$right 0$$bindloadfilesilent F:\TCB\RedWater\R\R100000.txt

showbind "f" (toggle Fly) while Fly is on

> +down$$bindloadfilesilent F:\TCB\RedWater\F\F000000r.txt

showbind "f" (toggle Fly) while Fly is off

> +down$$powexectoggleoff Sprint$$powexectoggleon Fly$$up 1$$down 0$$forward 0$$backward 0$$left 0$$right 0$$bindloadfilesilent F:\TCB\RedWater\BO\BO000000.txt

Sorcery/Mystic Flight seems to work fine.

(I did see you updated, but it doesn't seem like it changed any of the bind writing, only configuring in-software, so I've been lazy and haven't updated.)

**Comment by emersonrp** [comment]
I have a fix for the up key (and the down key) not toggling powers correctly, but it's deep in the innards of the SoD code, so I need to test it pretty rigorously with other non-Fly configurations, as well as with Fly without Hover.  This may take a bit.

**Comment by emersonrp** [comment]
I've created a prerelease with some Speed-on-Demand code changes that fix the Fly/Hover issue, as best I can tell, and don't immediately destroy the universe for other configurations.  Still, it's not fully shaken out, so please try it out with any toons you have with various movement powers to see if it acts as you'd expect.

https://github.com/emersonrp/bindcontrol/releases/tag/fly_vs_hover_test

**Comment by xizar** [comment]
Testing your "fly_vs_hover_test" build:

Using it on a fly/hover toon, it seems fine.  It has a slight weirdness where sometimes toggling on flight seems to activate both Hover and Fly but I think this is because it turns on fly and goes into the "blast off" phase.  If you stop pressing the key for "up" too soon, it will turn on hover, stop going up, but fail to turn off fly.

You can also get this to happen by tapping left/right/forward/back, though it will only turn on fly and not turn on hover.

I'm pretty certain this is due to latency and is nothing to do with the binds.

Plain old Mystic Flight wouldn't have evinced any of these issues.

I don't have a Mystic Flight/Hover toon to test that out, and no freespecs I can burn on testing that out. (I'm new to the game so buying one isn't really on the table, either).  That said, I don't know if the toggling would be desirable as turning off Mystic Flight means you lose the Translocation (though perhaps the user could make that decision for themselves).

**Comment by emersonrp** [comment]
Yeah that all sounds like latency / lag with the bind_load_file magic that speed on demand does.  I'd hoped that in 2024 with SSDs and 3+GHz CPUs and so forth that this wouldn't be a problem any more, but I see it a little bit too, so it's probably the general case and not the exception.

I'm thinking of experimenting with re-ordering the bits inside the bind strings to see if that helps.  I'm not sure it will, and it might cause different lag-based problems like directional motion getting stuck on, but it's worth a tinker.  

I'm going to open a new issue for that, and will close this one once I am satisfied I haven't blown up some important existing SoD functionality with this change, and have shipped an actual release with this code.

**Comment by emersonrp** [comment]
Released v0.16 which contains these changes.  There might be new bugs, please file new issues unless this "up" behavior re-emerges.
