### ISSUE TITLE
"Select Key" window Not Receiving any inputs

### ISSUE THREAD

**Issue by Premmyhub** [emersonrp/bindcontrol#3]
Currently this update does not recognize inputs from controllers, keyboards, or mouse Buttons when using the Key select menu. 
All menu Options are selectable as normal, but any attempt to input a key for a bind in any of the tabs yields no response. 

Pressing the Return/Enter Key Closes the window, The 'Ok" and "Cancel" menu options are selectable, and the "Bind left/Right mod keys Separately" checkbox is selectable

Things that still seem to Work as Usual:

All of the the options under "Profile" Help" and "Log" seem to function as usual
The "write Binds" function works as usual
All interactable Options elements In the "General" "Gameplay" "Custom Binds" "speed on Demand" "inspiration Popper" and "Mastermind/Pet Binds" tabs

**Comment by emersonrp** [comment]
Ah, I already see what's wrong, in addition to the obvious problem that I'm not testing Windows well enough.  I'll have a fix out shortly.  Thanks and sorry for the runaround.

**Comment by emersonrp** [comment]
I found the behavior you're talking about.  It mostly seems to manifest if no controller was detected at all -- the code naively assumed the existence of one and silently crashed if none was found.  I fixed that bug and I feel like it's acting better in general.  Please check out the controller-0.3 release and let me know your luck.  If it starts detecting keys and mouse clicks but not controller input, please make sure Windows is seeing the controller correctly.  I know that's sort of obvious, but wanting to make sure.

**Comment by emersonrp** [comment]
I've released the existing state of the controller support as version 0.13.  Please check it out if you get a chance and update this issue or file new ones as you find things.  Thanks!

**Comment by JamzTheMan** [comment]
I don't think this is working still? 0.13.1 worked but any of the builds after won't let me select a key bind, just stays red after selecting a key and pressing ok.

Windows 11, no controller enabled/on, just using keyboard/mouse.
(also, same issue on new buffer binding for pets/teammates)

![image](https://github.com/emersonrp/bindcontrol/assets/8051654/f1b7fe01-5eb1-4ed9-a753-2b9e9dbffeeb)

**Comment by emersonrp** [comment]
I've just released 0.13.5.1 which fixes this for me.  Please let me know your luck.  I apologize for the several cranky builds recently;  I'm away from my normal dev environment for a while and my whole rhythm is off.

**Comment by JamzTheMan** [comment]
0.13.5.1 won't launch for me at all, it seems to immediately crash/close before opening any windows.

**Comment by emersonrp** [comment]
That... is unexpected.  Let me try to work out why that would be.  It launches fine for me, so that's a little startling, as I'm also Win11, no controller, just as you mentioned.  I'm on it.

**Comment by emersonrp** [comment]
Please try out 0.13.5 -- I can't imagine how the differences between it and 0.13.5.1 are broken for you, but it's possible.  The change from 0.13.4 to 0.13.5 is isolated to the bugfix we're discussing here.  We might be in for a couple of rounds of "try it now" since I'm not seeing the same behavior.  Thanks for your patience.

https://github.com/emersonrp/bindcontrol/releases/tag/v0.13.5

**Comment by JamzTheMan** [comment]
OK, so now I can't seem to open/run any version other than the self contained `BindControl-0.13.1-windows.exe`

I *was* able to run earlier versions but now I can't... It doesn't look like windows has quarantined them. I'll keep trying but at a loss on why they just don't run.

Is there a way to see any sort of logging?

**Comment by JamzTheMan** [comment]
OK, so I downloaded the source, installed Python 3.11 + wxPython and tried running it I get this...

```
C:\coh\source\bindcontrol [main ≡]> python .\BindControl.py
Traceback (most recent call last):
  File "C:\coh\source\bindcontrol\BindControl.py", line 230, in OnInit
    self.Main = Main(None)
                ^^^^^^^^^^
  File "C:\coh\source\bindcontrol\BindControl.py", line 54, in __init__
    self.Profile.doLoadFromFile(filename)
  File "C:\coh\source\bindcontrol\Profile.py", line 273, in doLoadFromFile
    cbpage.AddBindToPage(bindpane = bindpane)
  File "C:\coh\source\bindcontrol\Page\CustomBinds.py", line 82, in AddBindToPage
    bindpane.BuildBindUI(self)
  File "C:\coh\source\bindcontrol\UI\SimpleBindPane.py", line 37, in BuildBindUI
    pbb = PowerBinderButton(pane, BindContentsCtrl, powerbinderdata)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\coh\source\bindcontrol\UI\PowerBinderDialog.py", line 191, in __init__
    self.PowerBinderDialog = PowerBinderDialog(self.Parent, init)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\coh\source\bindcontrol\UI\PowerBinderDialog.py", line 73, in __init__
    if init: self.LoadFromData(init)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\coh\source\bindcontrol\UI\PowerBinderDialog.py", line 80, in LoadFromData
    newCommand = commandClass(self.EditDialog, data)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\coh\source\bindcontrol\UI\PowerBinderDialog.py", line 230, in __init__
    self.UI = self.BuildUI(dialog)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\coh\source\bindcontrol\UI\PowerBinderDialog.py", line 234, in BuildUI
    def BuildUI(self, dialog)   : return wx.Sizer()
                                         ^^^^^^^^^^
TypeError: wx._core.Sizer represents a C++ abstract class and cannot be instantiated
OnInit returned false, exiting...
C:\coh\source\bindcontrol [main ≡]> git pull -r
Already up to date.
```

**Comment by JamzTheMan** [comment]
OK, so I asked co-pilot (since I'm more of a Java guy and not much up on Python) and it fixed the code so I can run the latest source now :)

![image](https://github.com/emersonrp/bindcontrol/assets/8051654/2870ccf2-cc1f-4a29-bfb7-d0773a92e0f1)

**Comment by emersonrp** [comment]
Ah I see, that is interesting.  Strange that it suddenly started acting up for you just now, but yes that one line did change between 0.13.1 and 0.13.2.

I've made a 0.13.6-pre1 for you please to test running from the ZIP file and/or from source.  The only change is making that call to wx.Sizer instead be to wx.BoxSizer.  It really shouldn't have been a problem but clearly it was, so I'm happy to make that change.  Check it out and let me know.  If it works, I'll bundle up a proper 0.13.6 and we'll call it a day.

Thanks for digging in to find where it was blowing up.  Weird that it worked (and still works) fine for me.

https://github.com/emersonrp/bindcontrol/releases/tag/v0.13.6-pre1

**Comment by emersonrp** [comment]
Also I am totally down with getting up to speed on Github Actions to do some of the legwork of building, as my multi-step manual process is fraught with peril.  Any help would be appreciated.

https://github.com/emersonrp/bindcontrol/issues/12

**Comment by JamzTheMan** [comment]
> Ah I see, that is interesting. Strange that it suddenly started acting up for you just now, but yes that one line did change between 0.13.1 and 0.13.2.
> 
> I've made a 0.13.6-pre1 for you please to test running from the ZIP file and/or from source. The only change is making that call to wx.Sizer instead be to wx.BoxSizer. It really shouldn't have been a problem but clearly it was, so I'm happy to make that change. Check it out and let me know. If it works, I'll bundle up a proper 0.13.6 and we'll call it a day.
> 
> Thanks for digging in to find where it was blowing up. Weird that it worked (and still works) fine for me.
> 
> https://github.com/emersonrp/bindcontrol/releases/tag/v0.13.6-pre1

That did it! All working! 

No idea why it just started happening, my only thought is that maybe I didn't delete the "bindcontrol" dir before unzipping a new version so maybe an old lib or something allowed it to work? Very strange none the less but thanks for working with me to create a fix!

**Comment by emersonrp** [comment]
OK, 0.13.6 released, and I'm closing this.  Whew.  Thanks again for your help tracking this down.

https://github.com/emersonrp/bindcontrol/releases/tag/v0.13.6
