### ISSUE TITLE
Warshade's Shadow Step isn't present in the SoD panel

### ISSUE THREAD

**Issue by xizar** [emersonrp/bindcontrol#31]
Warshade's Shadow Step isn't present as a teleport in the SoD panel.

It seems like it still gets a bind for some reason.  (bound to "shift")

It also appears that Peacebringer's flight abilities aren't, either.

**Comment by emersonrp** [comment]
Hmm, using 0.17.3 should have the Flight group show up for Peacebringers, with "Energy Flight" selected and a "Has Combat Flight" checkbox.  (Quantum Flight still isn't in there, very soon.)  0.17.1 should have had Warshade's "Shadow Step" show up with the Teleport group.  It's working for me.  Can you attach profiles where it's not appearing as expected?

**Comment by xizar** [comment]
Mea culpa.  You updated when I wasn't looking.
