### ISSUE TITLE
PelSel Text files are generated even if you do not check the boxes. 

### ISSUE THREAD

**Issue by autobotcoop** [emersonrp/bindcontrol#37]
![image](https://github.com/emersonrp/bindcontrol/assets/39393574/6b80dbae-806f-4fd3-ac6c-f15d9909e73b)
![image](https://github.com/emersonrp/bindcontrol/assets/39393574/300ca860-1f13-46db-ab01-e69d34833a98)
![image](https://github.com/emersonrp/bindcontrol/assets/39393574/4d172264-446b-4757-8db5-9482cc6fbd95)

Probably just a bug, figured I'd log it anyway.

**Comment by emersonrp** [comment]
Oh yeah that's just a bug.  Should be a quick fix when I get to it.

**Comment by emersonrp** [comment]
Yeah found that.  It's a small enough fix and a minor enough bug that I'm not going to roll a special release just for this one thing.  I've queued up the fix and it'll ride along with whatever the next release is.

**Comment by emersonrp** [comment]
Released with v0.17.10
