### ISSUE TITLE
Dueling Scrollbars 

### ISSUE THREAD

**Issue by autobotcoop** [emersonrp/bindcontrol#38]
Once your bind list gets long enough, two scrollbars will appear. 
![image](https://github.com/emersonrp/bindcontrol/assets/39393574/fb74d794-5905-4194-bd38-23c23d1f99d0)

**Comment by emersonrp** [comment]
Ah yeah I've been meaning to fix that for a little bit and forgot about it.  Originally the window wasn't resizeable so the bind list needed its own scrollbar, which is still in there.  Now that the whole window does the right thing with scrolling the contents, that one can come out.  Thanks for the reminder.

**Comment by emersonrp** [comment]
This overlaps / is influenced by #14

**Comment by emersonrp** [comment]
This has been fixed in the main branch and will be part of the next release.

**Comment by emersonrp** [comment]
Released with v0.17.10

**Comment by emersonrp** [comment]
Reopening this -- there's correctly just one scrollbar, but the outer pane still scrolls with the mousewheel if the mouse is just in the right place.  Need to turn off scrolling altogether in the outer pane.

**Comment by emersonrp** [comment]
@autobotcoop - are you running on Linux?  Those look like GTK scrollbars in your screenshots.  I'd thought you were running on Windows.  I might just be mistaken, though heh.

**Comment by autobotcoop** [comment]
Windows 11.

**Comment by emersonrp** [comment]
OK excellent.  The current state of the Custom Binds tab is a littlle wonky on Linux, and since you seem to be spending a lot of time in there, I wanted to make sure I hadn't broken your workflow.  I think Windows is behaving correctly now with respect to the scrollbars, mostly, apart from still scrolling the whole window if you have your mouse pointer at just exactly the right place and use the mousewheel.

**Comment by autobotcoop** [comment]
You're right, I am spending a lot of time in there. 
What I'm doing is looking over 
[stub.txt](https://github.com/user-attachments/files/15749109/stub.txt)
[COMMON.txt](https://github.com/user-attachments/files/15749111/COMMON.txt)

And figuring out what functions I want to duplicate for a "Common" profile.

**Comment by emersonrp** [comment]
Just released 0.17.10.1, a minor bugfix that makes the Custom Bind tab's scrolling behavior correct and deterministic on Linux and Windows, knock wood.  Re-closing this.
