### ISSUE TITLE
UI Suggestion: Freeze Tabs and New Bind Buttons in Window

### ISSUE THREAD

**Issue by autobotcoop** [emersonrp/bindcontrol#39]
![image](https://github.com/emersonrp/bindcontrol/assets/39393574/04436402-4d79-446c-bf01-b93a53b9f71b)

Using Excel Terms to try and explain what I want to suggest. As my list grows, it would be nice for the items in above picture to be always visible.

**Comment by emersonrp** [comment]
I'm actually gonna close this one because it's going to be the same fix as #38 -- the plan is that there will be a single scrollbar that will do the right thing including leaving those UI elements "frozen" at the top.  The undesirable behavior is because the "wrong" scrollbar is scrolling.
