### ISSUE TITLE
Mousewheel Bind

### ISSUE THREAD

**Issue by autobotcoop** [emersonrp/bindcontrol#42]
Had to add this to the reset file manually. 

MOUSEWHEEL "+camdistadjust$$playerturn"

**Comment by emersonrp** [comment]
Because camdistadjust isn't available, right?  Not that mousewheel didn't work?  Need to suss out where it makes sense to add that command into powerbinder.

**Comment by autobotcoop** [comment]
Scrolling the mousewheel in the bind box didn't work.

**Comment by emersonrp** [comment]
Oh that's no good.  OK I'll see what is up with that.  That used to work.

**Comment by emersonrp** [comment]
OK this is fixed in the main branch and will be part of the next release.

**Comment by emersonrp** [comment]
Fixed in v0.17.10.2

https://github.com/emersonrp/bindcontrol/releases/tag/v0.17.10.2
