### ISSUE TITLE
Custom Chat Colors Save/Load

### ISSUE THREAD

**Issue by autobotcoop** [emersonrp/bindcontrol#43]
Where do the Custom Chat Colors get written? I couldn't find it. 

I had to manually edit a file I created, Duke-Options.txt to save/load them.

**Comment by emersonrp** [comment]
Everything is saved into the Profile somewhere.  The chat colors from the General tab should be up near the top, and look like:

    "ChatBorder": "#000000",
    "ChatBackground": "#FFFFFF",
    "ChatForeground": "#000000",

If you have chat colors in a custom bind, they'll be down in the "CustomBinds" section, which should have a short chunk of config for each custom bind inside it.

Is that what you were asking?

**Comment by autobotcoop** [comment]
Yes. For some reason, they weren't loaded into the game though and had to be inputted through the method above.

**Comment by emersonrp** [comment]
So, ok, it didn't save selected chat colors into the Profile, or didn't write them into the bindfiles?  The ones in the General tab, or ones in specific custom powers?

**Comment by autobotcoop** [comment]
It saved them into the profile, but not the bind files.

**Comment by emersonrp** [comment]
Can you attach the profile file where this is happening?  Trying to make this happen but it seems to be working for me.  Thanks!

**Comment by autobotcoop** [comment]
[Duke.zip](https://github.com/user-attachments/files/15753409/Duke.zip)

Could also be user error. 😅

**Comment by emersonrp** [comment]
Could be, but let's make sure.  So I am not immediately seeing any problems with the reset.txt file this writes out, and it's chock-full of chat colors.  Which bind(s) is/are not showing colors like you expect?

**Comment by autobotcoop** [comment]
Okay, I misunderstood how it works. 

What I thought:
* This will make the text boxes these colors by default with little to no fiddling on my part. 

Reality:
* The chat channel has to be selected, then enter, then you have to go to end of line, and start typing.

**Comment by emersonrp** [comment]
Oh yeah, each of BindControl's text color schemes is per-tell, it doesn't set anything globally.  I'm not sure it's possible to set global chat colors in any way except through the options dialog.  So yeah, it's part of the "start chat" bind, which needs to have the channel already selected.  This could possibly be improved, open to suggestion.  Also the part where you have to go to the end of the line manually is irritating but I think it's just how the game handles things.

**Comment by autobotcoop** [comment]
I'll have to write a FAQ for you. 😂
