### ISSUE TITLE
Tray2 in Use Power from Tray Dropdown

### ISSUE THREAD

**Issue by autobotcoop** [emersonrp/bindcontrol#45]
![image](https://github.com/emersonrp/bindcontrol/assets/39393574/3235d737-fa78-4cb2-afcd-93309bee5869)

**Comment by emersonrp** [comment]
Oh just that it's missing the space between "Tray" and "2" in the picker label?  Got it, will be fixed in the next release.  Good eye.

**Comment by emersonrp** [comment]
Fixed in v0.17.10.2

https://github.com/emersonrp/bindcontrol/releases/tag/v0.17.10.2
