### ISSUE TITLE
Feature Suggeestion: Tray Tab

### ISSUE THREAD

**Issue by autobotcoop** [emersonrp/bindcontrol#46]
Add Tray tab or add a section under the Gameplay Tab
![image](https://github.com/emersonrp/bindcontrol/assets/39393574/4cf6f15e-bf34-4a65-a718-126d1d4f1a03)

In the tray tab, the user could assign:
* 1-0 to tray 1
* CTRL+1-0 to tray 2
* SHIFT+1-0 to tray 3
* etc etc.

**Comment by emersonrp** [comment]
I like the idea of being able to twiddle the tray mappings.  Dunno if I want to make a whole new tab for that, though I'm gonna mull the idea.  Would that make sense in the Gameplay tab, which needs a little layout love anyway?

**Comment by autobotcoop** [comment]
Yes it would. 

Maybe you could add custom window colors there too? 

Some people, myself included, try to theme everything for our characters, It might make more sense under the General Tab, but that seems a little crowded right now.

**Comment by emersonrp** [comment]
I'm leaning toward tray stuff in Gameplay, cause yeah General's sorta full.  I suppose I could just get used to the idea that BindControl needs either more tabs or more screen real estate.

For window colors, I totally like that idea.  It would make most sense, though, I guess, to put that in as part of the Reset sequence, but that one is jam-packed already, to the point where adding anything substantive very likely will overrun the 255-character limit for individual binds.

Would a good compromise be to add that in as a PowerBinder option so you can bind a key to it?  Could then bind different keys to different window color schemes, though if you're theming per-character, that might be overkill.

Another alternative would be to add a line to the "copy and paste this into the game" dialog that comes up when you Write Binds -- I've been pondering doing that anyway for controller `/extra_modifiers` etc, but I need to test whether pasting multiple lines into the game works as intended, or if that puts the burden on the player to copy and paste each line if there's multiple of them.

Thoughts?

**Comment by autobotcoop** [comment]
Adding that to the power binder is fine! 

`F12 "wdw_load_file C:\binds\Duke\Duke-window.txt"`
`ALT+F12 "wdw_save_file C:\binds\Duke\Duke-window.txt"`
`SHIFT+F12 "window_color 15 32 73 150"`

As an example.

**Comment by autobotcoop** [comment]
> I've been pondering doing that anyway for controller /extra_modifiers etc, but I need to test whether pasting multiple lines into the game works as intended, or if that puts the burden on the player to copy and paste each line if there's multiple of them.

Couldn't you paste multiple lines with:
`line1$$line2$$line3`


I use `TILDE "enterbasefrompasscode COSMICTRANSPORT-6608$$enterbasefrompasscode NoGood-179$$enterbasefrompasscode TheProject-16"` since I play mostly on Rebirth, and occasionally on HC

**Comment by emersonrp** [comment]
Broke with /windowcolor request out into its own issue #52

**Comment by emersonrp** [comment]
![TrayCtrls](https://github.com/emersonrp/bindcontrol/assets/307232/96a26c06-f22c-420e-b7f5-0b3cf59305a5)

Starting work on this.  This is just super rudimentary "add in the buttons" and is not at all how the final product will look.

**Comment by autobotcoop** [comment]
Pretty much what I was looking for since my brain has hard-wired row 2 as ctrl+#

**Comment by emersonrp** [comment]
Dunno if you know but there's the "Keybind Profile" notion at the top of the Keybindings tab in the in-game options, that you can set to "Classic" to get back the older pre-27-7 binds.  Not sure if it's sticky between toons, though.  Still easier than manually twiddling at least ten binds.  But I'm still bashing on this because I want basically every slash command to be accessible to BindControl including "powexec_tray"

**Comment by autobotcoop** [comment]
If I were to design it myself and wanted to keep it simple, I think I would go with:

"What modifier key do you want to use for row two? [Box]" etc.  

I understand what you're doing though, as there's always edge cases out there that want to control every bind.

**Comment by emersonrp** [comment]
Back when I played WoW, I had "1" through "-" mapped to the eleven bar buttons you'd expect, but specifically mapped "=" to "mount up" which because of addons reasons wasn't just something I could drag to the bar at the time.  I like the notion of "fill this row with Ctrl + the numbers" and I'll see if there's some hybrid way to add that in simply.

**Comment by autobotcoop** [comment]
> Dunno if you know but there's the "Keybind Profile" notion at the top of the Keybindings tab in the in-game options, that you can set to "Classic" to get back the older pre-27-7 binds. Not sure if it's sticky between toons, though. 


Must be a HC thing as I only see a Default and Original on the Rebirth Client, but good to know! 

I suppose I could just do it manually in the client, but I'm already using BindControl  for making this easier.

**Comment by emersonrp** [comment]
Oh right Rebirth yes.  Sorry, I know that and it just falls out of my head.  Yeah the "Classic" vs "Modern" thing is a February change on Homecoming.  And yeah I am all-in on helping you be able to manage everything in one place.

**Comment by emersonrp** [comment]
Just shipped the bare-bones version of this as v0.17.12

https://github.com/emersonrp/bindcontrol/releases/tag/v0.17.12

**Comment by autobotcoop** [comment]
https://github.com/emersonrp/bindcontrol/issues/53#issue-2347507634

**Comment by autobotcoop** [comment]
Material for FAQ/Documentation: 
* If you want to flip 2 rows around, uncheck one of the rows you want to rebind, so BC doesn't throw conflicting bind alerts at you.

**Comment by emersonrp** [comment]
Oh interesting.  That's going to get worse whenever v0.18 finally creeps out -- its whole thing is more complete noticing and warning of conflicts, though I suppose it won't be any worse assuming you don't also have "Alt-2" or whatever bound to something else in a remote corner of the app.  This is a good argument for being able to set the whole row at once.  Hmm pondering.

**Comment by autobotcoop** [comment]
Suggestion: 

Change server tray to tray 4. (`ALT+0 "powexec_tray 10 4"`)
* Server Tray is usually for very temporary powers, no real reason to bind it. Some sicko will though.

**Comment by emersonrp** [comment]
My notion was to match BindControl's tray UI up with the in-game lower-right tray UI, and leave "extra" trays alone for now.  I guess the feature could expand to allow for selecting which tray rows are shown in the UI instead of just having a static four rows which for most people will be disabled and taking up space.  Gonna keep pondering this.  I feel like this feature is not in its final form for sure.

**Comment by xizar** [comment]
Regarding using a single key to bind multiple settings (like all the color schemes) mentioned toward the bottom of https://github.com/emersonrp/bindcontrol/issues/46#issuecomment-2156686147

I would note that the popmenu TSPMenu  (mentioned in https://forums.homecomingservers.com/topic/27085-optimal-badgeplaque-collection-path-popmenu/ with a link to the popmenu in the dude's forum sig) handles a way to rotate through a a sequence of binds by mashing the same bindkey.

You could do something similar with a palette of window colors.  This would let clark kent's windows be blue and white, then mash the button so the windows go red and blue when he changes costume, then turn mash the button again for black and grey when he masquerades as batman, before cycling back to blue and white when it's time to clock in at the daily planet.

(I guess I fixated on the costume/window color combos... not really suggesting, just trying to provide a scenario where this method might be reasonable.)

**Comment by emersonrp** [comment]
BindControl already can do exactly that (apart from the "windowcolor" thing not quite yet being shipped) -- you'd make a Complex Bind, with each step having a "windowcolor" command and a "costume change" command, and the key for the Complex Bind would cycle through the steps.

(It's more than a little bit possible that Complex Binds are underexplained and need better visibility.)

**Comment by xizar** [comment]
Oh, yeah.  The whole "custom bind" tab feels underexplained.

I tried using the "simple bind" to bind some powers and decided it was more trouble than it was worth and just went back clicking buttons on the power tray.

(It's not helped that you reference "incomplete and unofficial guide to bind" is it's also not the most plainly written thing.

**Comment by autobotcoop** [comment]
[This file](http://www.shenanigunner.com/GABS%20Guide%20v1-0-0.pdf) helped me start this journey on binding. 

I need to make time and start writing documentation.md for emerson.

**Comment by emersonrp** [comment]
There is a rudimentary manual that covers most things at a pretty high level, under the "Help" menu.  More documentation is always on the TODO list.  I also need to sprinkle more of the little popup help buttons around for sure.

**Comment by emersonrp** [comment]
We've drifted pretty far afield from the original feature suggestion in this comment thread, but I thought I'd go ahead and mention that I just added little help buttons to the Custom Binds page that give at least an overview of what Simple, Complex, and Buffer Binds are and do.

https://github.com/emersonrp/bindcontrol/releases/tag/v0.19.0.2

**Comment by emersonrp** [comment]
Just released 0.19.4, which adds "Fill" buttons to the right of the powers tray rows.  You can click it to fill the associated tray with 1 - 0.  Alt-click it for Alt+1 - Alt+0 etc etc for each modifier key.

https://github.com/emersonrp/bindcontrol/releases/tag/v0.19.4

**Comment by emersonrp** [comment]
I suspect the tray buttons aren't in their utter final form, but with the "Fill" button in place, I feel like this feature request is complete, and we can iterate new suggestions as new issues.  Just housecleaning.
