### ISSUE TITLE
Opening the program with a longer list of CustomBinds takes a while

### ISSUE THREAD

**Issue by emersonrp** [emersonrp/bindcontrol#48]
See if there's some way to speed up loading custom binds.  Alternatively, restructure to show the window sooner but throw up a "busy" cursor while loading.

**Comment by emersonrp** [comment]
Could be the part where the app creates a PowerBinderDialog and PowerBinderEditDialog for like every step in every bind.  Need to rework this to reuse the same dialog, maybe?

**Comment by emersonrp** [comment]
A quickfix (lazy-create dialogs only when shown) has been implemented on main and will ship with the next release.

**Comment by emersonrp** [comment]
Shipped the quickfix.  @autobotcoop can you see if you notice any performance gains opening up Profiles with large numbers of custom binds?  I suspect it might be noticeably faster.

https://github.com/emersonrp/bindcontrol/releases/tag/v0.17.12.3

**Comment by autobotcoop** [comment]
If I had to guess, I'd say, a 30-45 second decrease in loading time. Well done.

**Comment by emersonrp** [comment]
Oh that's fantastic.  I'm going to leave the bug open because I have one more idea for further improvement.  Delighted that this one worked out so well.

**Comment by emersonrp** [comment]
There was um a bit of a bug with saving Simple Binds created by this quickfix.  It's fixed in v0.17.12.5

https://github.com/emersonrp/bindcontrol/releases/tag/v0.17.12.5

I am sad to say that any Profile with Simple Binds that's been saved in the meantime -might- have had the state of the editing dialog lost.  This isn't terrible if you're not going to edit the steps of the bind, the raw contents are still there, but is still possible data loss, so I'm a bit bummed about that.

**Comment by emersonrp** [comment]
I'm going to go ahead and close this, as my other experiments aren't panning out, and #61 fell out of that process, so I'll continue there.
