### ISSUE TITLE
Add /windowcolor to PowerBinder

### ISSUE THREAD

**Issue by emersonrp** [emersonrp/bindcontrol#52]

**Comment by autobotcoop** [comment]
`F12 "wdw_load_file C:\binds\Duke\Duke-window.txt"`
`ALT+F12 "wdw_save_file C:\binds\Duke\Duke-window.txt"`
`SHIFT+F12 "window_color 15 32 73 150"`

**Comment by autobotcoop** [comment]
Add space checker to window_color string.
`window_color 15_32_73_150` Correct
`window_color 15__32_73_150"` Incorrect, results in a 0 G value.

**Comment by emersonrp** [comment]
/windowcolor is implemented and will be part of the next non-bugfix release.  Might toss /wdw_* in there for good measure, not sure yet.

**Comment by emersonrp** [comment]
Rudimentary window settings save/load will also ship in the next non-bugfix release.  It just uses a raw text entry to get the filename instead of like a file picker or something, but it defaults to "binds_dir\profile\windows.txt" which seems like a sane place to start.

**Comment by emersonrp** [comment]
These have shipped with v0.17.13.

https://github.com/emersonrp/bindcontrol/releases/tag/v0.17.13

**Comment by emersonrp** [comment]
Did a little more thinking about this, and I think the textctrl is actually the right solution.  Trying to make a file picker would involve selecting (or creating) a file that doesn't necessarily already exist, and that BindControl is not, itself, going to manipulate.  I'm gonna close this as implemented, and accept new issues if it's broken or wants specific improvements.
