### ISSUE TITLE
0.17.12 Unhandled Exception 

### ISSUE THREAD

**Issue by autobotcoop** [emersonrp/bindcontrol#53]
![image](https://github.com/emersonrp/bindcontrol/assets/39393574/aa32eefb-a7a4-463f-ad2d-fb35fe7427ab)

**Comment by emersonrp** [comment]
Wow ok looking

**Comment by emersonrp** [comment]
Something has clearly gone wrong in the automated build -- the ZIP file is nearly twice as big as it should be.  Digging in.

**Comment by emersonrp** [comment]
There we go:

https://github.com/emersonrp/bindcontrol/releases/tag/v0.17.12.1
