### ISSUE TITLE
PowerBinder Sprint & Autorun

### ISSUE THREAD

**Issue by autobotcoop** [emersonrp/bindcontrol#55]
Trying to reproduce this custom bind through powerbinder. 

`powexectoggleon Sprint$$autorun 1` results in 

![image](https://github.com/emersonrp/bindcontrol/assets/39393574/6a52c650-e8d8-427d-acad-4af5a7e3d69c)

It has something to do with selecting 0 or 1 with autorun.

**Comment by emersonrp** [comment]
I sorta see what's happening here.  I'm needing to disappear for a bit tonight but I'm on this.

**Comment by autobotcoop** [comment]
Self care is important!

**Comment by emersonrp** [comment]
Fixed.  That was a little embarrassing actually, I just forgot an important little flag and so radio buttons in one place were toggling off radio buttons in other places.

https://github.com/emersonrp/bindcontrol/releases/tag/v0.17.12.3
