### ISSUE TITLE
 Error: Error populating bind file: 'BindKey' 18.2

### ISSUE THREAD

**Issue by autobotcoop** [emersonrp/bindcontrol#63]
Not sure what this means 
[Duke.zip](https://github.com/user-attachments/files/15842306/Duke.zip)

**Comment by emersonrp** [comment]
Oh that's annoying.  Fixed:

https://github.com/emersonrp/bindcontrol/releases/tag/v0.18.2.1

**Comment by autobotcoop** [comment]
Fixed with new release.
