### ISSUE TITLE
Feature Request: Copy button next to bindloadfile string 

### ISSUE THREAD

**Issue by autobotcoop** [emersonrp/bindcontrol#64]
![image](https://github.com/emersonrp/bindcontrol/assets/39393574/1a0e0cbe-ffbf-4749-87a7-ee6e1fb77d3e)
A little copy button next to the string would be easier, in my opinion.

**Comment by emersonrp** [comment]
Not a bad idea.  I'll try to tinker that up.  I've been in that dialog anyway today, monkeying around with adding a list of what files were written.  Not in love with that yet, but this should be easy to add while I'm in there.

**Comment by emersonrp** [comment]
Easy peasy.  It's on the main branch now, and will ride along with whatever the next release is.

**Comment by emersonrp** [comment]
This has shipped with v0.19.  I also did a little fiddling to try to make sure the field is wide enough for the entire string, for people who still want to select it directly.

https://github.com/emersonrp/bindcontrol/releases/tag/v0.19
