### ISSUE TITLE
Cosmetic issue with "general" tab having a little red ecks over it in v0.21

### ISSUE THREAD

**Issue by xizar** [emersonrp/bindcontrol#72]
![BindControl_h5z6wGZKmZ](https://github.com/emersonrp/bindcontrol/assets/5367098/ff1156c1-609a-4b37-858e-d94a62a3d244)

The box does not appear on initial load of a profile, only after making a new one or loading an existing one.

The little red ecks seems to be nonfunctional.

**Comment by emersonrp** [comment]
Hmm I can't get this to happen in Window 10 or 11.  Does it do it reliably?  If so, what are the exact steps you take to make it happen?

**Comment by xizar** [comment]
I had not noticed what triggered it until trying to reproduce it from scratch.  (After it appears, it persists, and I didn't notice it until later.)

It's triggered by writing binds with a Mastermind that does not have named pets, or that has pet names that will otherwise pop up the warning box about pet names.

**Comment by emersonrp** [comment]
Hm I still can't get this to happen exactly, though I think I know what's happening.  I need to tinker with the little "InfoBar" that's supposed to live at the bottom to surface errors and warnings, which seems to migrate to the top occasionally.  It shouldn't ever show that X if it's not, itself, visible, though.  You're using the binary release?

**Comment by emersonrp** [comment]
Aha!  It shows up if the InfoBar is triggered by an error or warning, and the InfoBar is no longer appearing as intended.  Will fix.

**Comment by emersonrp** [comment]
OK, the InfoBar should now stay at the bottom and therefore appear correctly.  The fact that you were getting the InfoBar in the first place (or, not getting it because of the bug, but getting the X) means that something broke somewhere and probably needs to be reported as a bug.  The InfoBar should now provide some info as intended.

https://github.com/emersonrp/bindcontrol/releases/tag/v0.21.0.2

**Comment by emersonrp** [comment]
I've been seeing the infobar appearing in the right place for quite a while now, and so I think this issue is fixed.  Please reopen if you see it again.
