### ISSUE TITLE
Unkown command: back

### ISSUE THREAD

**Issue by lee-bcbs** [emersonrp/bindcontrol#9]
Looks like the S binding to 'back' should be 'backward' instead?

CoH chat shows "Unknown command: back" on a new profile on Homecoming.

**Comment by emersonrp** [comment]
Wow, you might apparently be the first person to use BindControl without turning on the speed on demand stuff, 'cause that's never come up before.  I'll fix up the basic bind asap and do a bugfix release.  Thanks!

**Comment by emersonrp** [comment]
Fixed in version 0.13.1
